spring:
  cloud:
    config:
      server:
        native:
          search-locations: ./git-repo
        git:
          uri: https://gitlab.com/szmengran/microservices-repo.git
          basedir: ./git-repo
          username: ${GITLAB_USERNAME}
          password: ${GITLAB_PASSWORD}
