logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.security: DEBUG
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: dev
ribbon:
  ReadTimeout: 120000 #请求处理的超时时间 
  ConnectTimeout: 30000 #请求连接的超时时间