logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.security: DEBUG

spring:
  application:
    name: cloud-config-server
  profiles:
    active: ${ENVIRONMENT}
  cloud:
    config:
      server:
        native:
          search-locations: ./config_repo_git
        git:
          uri: https://gitlab.com/suntak/cloud-config-repo.git
          basedir: ./config_repo_git
          username: ${GITLAB_USERNAME}
          password: ${GITLAB_PASSWORD}

ribbon:
  ReadTimeout: 120000 #请求处理的超时时间 
  ConnectTimeout: 30000 #请求连接的超时时间