spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/szmengran/microservices-repo.git
          basedir: ./config_repo_git
          username: ${GITLAB_USERNAME}
          password: ${GITLAB_PASSWORD}
