eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 2 # 发呆时间，即服务续约到期时间（缺省为90s）
  server:
    peer-node-read-timeout-ms: 6000
mybatis:
  configuration:
    jdbc-type-for-null: 'null'
logging:
  level:
    org.springframework.security: debug
    com.szmengran: debug
    com.netflix: warn
ribbon:
  ReadTimeout: 120000 #请求处理的超时时间
  ConnectTimeout: 30000 #请求连接的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,health,info #消息总线配置