eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  cloud:
    config:
      fail-fast: true
swagger:
  enable: false
security:
  oauth2:
    client:
      clientId: api
      clientSecret: api
      accessTokenUri: http://oauth2:10002/api/v1/oauth2/oauth/token
      user-authorization-uri: http://oauth2:10002/api/v1/oauth2/oauth/authorize
    resource:
      tokenInfoUri: http://oauth2:10002/api/v1/oauth2/oauth/check_token
      accessTokenUri: http://oauth2:10002/api/v1/oauth2/oauth/access_token
      userAuthorizationUri: http://oauth2:10002/api/v1/oauth2/oauth/authorize
      user-info-uri: http://oauth2:10002/api/v1/oauth2/users/principal