version: '3.1'
services:
  config:
    image: registry.cn-beijing.aliyuncs.com/szmengran/config:$INFRASTRUCTURE_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - ENVIRONMENT=$ENVIRONMENT
      - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka
      - GITLAB_USERNAME=$GITLAB_USERNAME
      - GITLAB_PASSWORD=$GITLAB_PASSWORD
    ports:
     - "10001:10001"
networks:
  default:
    external:
      name: cloud
