version: '3.1'
services:
  eureka:
    image: szmengran/eureka:$CLOUD_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
    ports:
     - "8761:8761"
networks:
  default:
    external:
      name: cloud
