version: '3.1'
services:
  eureka:
    image: registry.cn-beijing.aliyuncs.com/szmengran/eureka:$INFRASTRUCTURE_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - ENVIRONMENT=$ENVIRONMENT
      - CONFIG_SERVER_ADDRESS=http://config:10001
    ports:
     - "8761:8761"
networks:
  default:
    external:
      name: cloud
