version: '3.1'
services:
  gateway:
    image: registry.cn-beijing.aliyuncs.com/szmengran/gateway:$INFRASTRUCTURE_VERSION
    restart: always
    environment:
      - KAFKA_SERVER=$KAFKA_SERVER
      - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka
      - CONFIG_SERVER_ADDRESS=http://config:10001
      - ENVIRONMENT=$ENVIRONMENT
    ports:
      - "10000:10000"
networks:
  default:
    external:
      name: cloud
