logging:
  level:
    org.springframework.security: INFO
    
ribbon:
  ReadTimeout: 120000 #请求处理的超时时间 
  ConnectTimeout: 30000 #请求连接的超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
            
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh #消息总线配置
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}

security:
  oauth2:
    resource:
      tokenInfoUri: http://localhost:10002/oauth/check_token
      accessTokenUri: http://localhost:10002/oauth/access_token
      userAuthorizationUri: http://localhost:10002/oauth/authorize
    client:
      client-id: cloud-engineering-order
      client-secret: 12345

spring:
  datasource:
    druid:
      common:
        read:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.0.117:3306/common?useSSL=false
          username: common
          password: Li123456
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
          stat-view-servlet:
            login-username: admin
            login-password: admin
            url-pattern: /druid
        write:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.0.116:3306/common?useSSL=false
          username: common
          password: Li123456
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
          stat-view-servlet:
            login-username: admin
            login-password: admin
            url-pattern: /druid
      sales:
        read:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.0.117:3306/sales?useSSL=false
          username: sales
          password: ${MYSQL_PASSWORD}
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
          stat-view-servlet:
            login-username: admin
            login-password: admin
            url-pattern: /druid
        write:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.0.116:3306/sales?useSSL=false
          username: sales
          password: ${MYSQL_PASSWORD}
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
          stat-view-servlet:
            login-username: admin
            login-password: admin
            url-pattern: /druid
      sms:
        read:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.0.117:3306/sms?useSSL=false
          username: sms
          password: Li123456
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
          stat-view-servlet:
            login-username: admin
            login-password: admin
            url-pattern: /druid
        write:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.0.116:3306/sms?useSSL=false
          username: sms
          password: Li123456
          driver-class-name: com.mysql.jdbc.Driver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
          stat-view-servlet:
            login-username: admin
            login-password: admin
            url-pattern: /druid
      cuxsoa:
        read:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:oracle:thin:@//cderpdb-scan.suntakpcb.com:1521/prod
          username: cux_soa
          password: cux_soa
          driver-class-name: oracle.jdbc.driver.OracleDriver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 1 from dual
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
        write:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:oracle:thin:@//cderpdb-scan.suntakpcb.com:1521/prod
          username: cux_soa
          password: cux_soa
          driver-class-name: oracle.jdbc.driver.OracleDriver
          initial-size: 2
          max-active: 5
          min-idle: 2
          max-wait: 60000
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 1 from dual
          validation-query-timeout: 60000
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
          max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
          filters: stat
