zuul:
  routes:
    cloud-admin-user:
      path: /**/cloud-admin-user/**
      serviceId: cloud-admin-user
      stripPrefix: false
      sensitiveHeaders:
    cloud-security-oauth:
      path: /**/oauth/**
      serviceId: cloud-security-oauth
      stripPrefix: false
      sensitiveHeaders:
    cloud-common-sms:
      path: /**/smses/**
      serviceId: cloud-common-sms
      stripPrefix: false
      sensitiveHeaders:
    cloud-suntak-sms:
      path: /**/suntaksms/**
      serviceId: cloud-suntak-sms
      stripPrefix: false
      sensitiveHeaders:
    cloud-suntak-ehr:
      path: /**/ehr/**
      serviceId: cloud-suntak-ehr
      stripPrefix: false
      sensitiveHeaders:
    cloud-suntak-activity:
      path: /**/activity/**
      serviceId: cloud-suntak-activity
      stripPrefix: false
      sensitiveHeaders:
    cloud-suntak-questionnaire:
      path: /**/questionnaires/**
      serviceId: cloud-suntak-questionnaire
      stripPrefix: false
      sensitiveHeaders:
    cloud-suntak-test:
      path: /**/test/**
      serviceId: cloud-suntak-test
      stripPrefix: false
      sensitiveHeaders:
    cloud-suntak-recruitment:
      path: /**/recruitment/**
      serviceId: cloud-suntak-recruitment
      stripPrefix: false
      sensitiveHeaders:
  host:
    connect-timeout-millis: 500000
    socket-timeout-millis: 100000
