zuul:
  routes:
    oauth:
      path: /**/oauth/**
      serviceId: oauth
      stripPrefix: false
      sensitiveHeaders:
  host:
    connect-timeout-millis: 500000
    socket-timeout-millis: 100000
