spring:
  redis:
      database: 0
      host: 192.168.0.112
      password: Li1234567890
      port: 6379
      pool:
          max-active: 8
          max-wait: 8
          min-idle: 0
          max-idle: 8
  datasource:
    druid:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/oauth?useSSL=false
        username: oauth
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 2
        max-active: 5
        min-idle: 2
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        validation-query-timeout: 60000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
        max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat
        stat-view-servlet:
          login-username: admin
          login-password: admin
          url-pattern: /druid
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/oauth?useSSL=false
        username: oauth
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 2
        max-active: 5
        min-idle: 2
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        validation-query-timeout: 60000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
        max-evictable-idle-time-millis: 3000000 #配置一个连接在池中最小生存的时间，单位是毫秒
        filters: stat
        stat-view-servlet:
          login-username: admin
          login-password: admin
          url-pattern: /druid